# Copyright (c) 2019 Ayoume Inc.
# All rights reserved.
#
# "Bash Settings" version 1.0
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#    * Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following disclaimer
# in the documentation and/or other materials provided with the
# distribution.
#    * Neither the name of Ayoume Inc. nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# ---
# Author: Zichoole
# E-mail: zichoole@gmail.com
# Date  : 2019-05-27 12:20:00
#
# ---
# Description:
#   Settings for bash shell.
#
#******************************************************************


#******************************************************************
#
# Term font must be "Meslo LG S DZ Regular 12pt".
#
#******************************************************************


#******************************************************************
#
# exports
#
#******************************************************************

export WORKSPACE="${HOME}/Workspace"
export POWERLINE_SHELL_HOME="${HOME}/.powerline-shell"


#******************************************************************
#
# pyenv
#
#******************************************************************

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export PIPENV_VENV_IN_PROJECT=1


#******************************************************************
#
# autoenv
#
#******************************************************************

#source $(brew --prefix autoenv)/activate.sh


#******************************************************************
#
# direnv
#
#******************************************************************

export DIRENV_ALLOW=${HOME}
export DIRENV_LOG_FORMAT=""
eval "$(direnv hook bash)"
#function show-virtualenv() {
#  if [ -n "${VIRTUAL_ENV}" ]; then
#    echo "($(basename ${VIRTUAL_ENV}))"
#  fi
#}
#export PS1="$(show-virtualenv)${PS1}"


#******************************************************************
#
# virtualenvwrappe
#
#******************************************************************

export VIRTUALENV_HOME="${HOME}/.virtualenvs"
#[ -s "${VIRTUALENV_HOME}/virtualenvwrapper.sh" ] && \
#  source "${VIRTUALENV_HOME}/virtualenvwrapper.sh"


#******************************************************************
#
# node
#
#******************************************************************

export NODE_PATH="/usr/local/lib/node_modules"
export NVM_DIR=${HOME}/.nvm
[ -s "${NVM_DIR}/nvm.sh" ] && source "${NVM_DIR}/nvm.sh"


#******************************************************************
#
# lscolors
#
#******************************************************************
#
#    1. directory
#    2. symbolic link
#    3. socket
#    4. pipe
#    5. executable
#    6. block special
#    7. character special
#    8. executable with setuid bit set
#    9. executable with setgid bit set
#    10. directory writable to others, with sticky bit
#    11. directory writable to others, without sticky
#
#******************************************************************
#
#    a black
#    b red
#    c green
#    d brown
#    e blue
#    f magenta
#    g cyan
#    h light grey
#    A bold black, usually shows up as dark grey
#    B bold red
#    C bold green
#    D bold brown, usually shows up as yellow
#    E bold blue
#    F bold magenta
#    G bold cyan
#    H bold light grey; looks like bright white
#    x default foreground or background
#
#******************************************************************

export LSCOLORS="exfxgxdxCxhxHxabagacad"
export CLICOLOR="yes"
export LS_OPTIONS="--color=auto"


#******************************************************************
#
# aliases
#
#******************************************************************

# bash
alias sh="bash"

# paths
alias c="cd"
alias dir="dir --color=auto"
alias vdir="vdir --color=auto"

# ls
alias ll="ls -Gl"
alias la="ll -Ga"
alias lh="ll -h"
alias l="ls -Gl"
alias ls="ls -G"

# vim
alias v="vim"
alias vi="vim"

# grep
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"

# tree
alias tree="tree -C"

# pipenv
alias prp="pipenv run python"
alias pun="pipenv run"
alias psh="pipenv shell; bash --login"


#******************************************************************
#
# coreutils
#
#******************************************************************

if brew list | grep coreutils > /dev/null; then
  export PATH="$(brew --prefix coreutils)/libexec/gnubin:${PATH}"
  alias ls='ls -F --show-control-chars --color=auto'
  eval `gdircolors -b ${HOME}/.dir_colors`
fi


#******************************************************************
#
# enable mouse scroll in vim
#
#******************************************************************

defaults write com.googlecode.iterm2 AlternateMouseScroll -bool true


#******************************************************************
#
# scutil
#
#******************************************************************

#sudo scutil --set HostName "ayoume.com"
#sudo scutil --set LocalHostName "localhost"
#sudo scutil --set ComputerName "Zich's Macbook Pro"


#******************************************************************
#
#   Front             Back             Color
#   ------------------------------------------
#   30                40               Black
#   31                41               Red
#   32                42               Green
#   33                43               Yellow
#   34                44               Blue
#   35                45               Purple
#   36                46               Cyan
#   37                47               White
#
#
#   Code              Meaning
#   ------------------------------------------
#   0                 OFF
#   1                 Highlight
#   4                 Underline
#   5                 Flicker
#   7                 Reverse
#   8                 Invisible
#
#*******************************************************************


#*******************************************************************
#
# prompt
#
#*******************************************************************

# random-emoji
function random-emoji() {
  local -r emojies=("🤔" "😃" "😂" "😊" "🤗" "😊" "😁")
  echo "${emojis[$((${RANDOM} % ${#emojies[@]}))]}"
}

# powerline-shell:
#   Use 'print(u'char'.encode('unicode_escape'))' by python to show unicode.
#   git clone https://github.com/banga/powerline-shell.git
function powerline-shell() {
  echo "$(${POWERLINE_SHELL_HOME}/powerline-shell.py $? 2> /dev/null)"
  export PS1="$(${POWERLINE_SHELL_HOME}/powerline-shell.py $? 2> /dev/null)$(random-emoji) "
}

# generate-prompt
function generate-prompt() {
  export PS1="$(powerline-shell)$(random-emoji) "
}

# prompt-command
export PROMPT_COMMAND="generate-prompt; ${PROMPT_COMMAND}"


#*******************************************************************
#
# language
#
#*******************************************************************

export LANG=en_US.UTF-8
export LC_COLLATE=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_MESSAGES=en_US.UTF-8
export LC_MONETARY=en_US.UTF-8
export LC_NUMERIC=en_US.UTF-8
export LC_TIME=en_US.UTF-8
export LC_ALL=en_US.UTF-8

